name: Ci

on: [pull_request, push]

jobs:
  lint:
    name: Lint
    runs-on: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "14"

      - name: Install Dependencies
        run: yarn install --frozen-lockfile

      - name: Lint Code (prettier)
        run: yarn run format

      - name: Lint Code (eslint)
        run: yarn run lint

  format:
    name: Format
    runs-on: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "14"

      - name: Install Dependencies
        run: yarn install --frozen-lockfile

      - name: Format Code
        run: yarn run format:write
